### PR TITLE
Allow to pass a model object to the listbox helper

### LINKED ISSUE #6: Allow to pass a model object to the listbox helper
To improve the flexibility of the listbox helper allow to pass a model object instance.

### PR DESCRIPTION
**Pull request by johanjanssens**
resolve #6

### CODE REVIEW

**Comment by johanjanssens** [comment]
@ercanozkaya Can you review this please ? Change is required for the tags helper to work correctly. See: https://github.com/joomlatools/joomlatools-framework-tags/blob/master/template/helper/listbox.php#L41

**Comment by rmdstudio** [comment]
@johanjanssens on line 277 it is still assumed that $config->model is **always** a string https://github.com/joomlatools/joomlatools-framework/blob/e86973d82e998dd4a1804ba948fe3a9563f9ed0a/code/libraries/joomlatools/library/template/helper/listbox.php#L277

**Comment by rmdstudio** [comment]
@johanjanssens try this implementation instead:

```
protected function _autocomplete($config = array())
    {
        $config = new KObjectConfigJson($config);
        $config->append(array(
            'name'     => '',
            'attribs'  => array(
                'id' => 'select2-element-'.mt_rand(1000, 100000)
            ),
            'model'    => KStringInflector::pluralize($this->getIdentifier()->package),
            'validate' => true,
            'prompt'   => '- '.$this->getObject('translator')->translate('Select').' -',
            'deselect' => true,
        ))->append(array(
            'element'    => '#'.$config->attribs->id,
            'options'    => array('multiple' => (bool) $config->attribs->multiple),
            'value'      => $config->name,
            'selected'   => $config->{$config->name},
        ))->append(array(
            'label'      => $config->value,
        ))->append(array(
            'text'       => $config->label,
            'filter'     => array('sort' => $config->label),
        ));

        //Add name to attribs
        $config->attribs->name = $config->name;

        if(!$config->model instanceof KModelInterface) {

            $config->append(array(
                'identifier' => 'com://'.$this->getIdentifier()->domain.'/'.$this->getIdentifier()->package.'.model.'.$config->model
            ));

            $model = $this->getObject($config->identifier);
        } else {
            $model = $config->model;
        }

        if (!$config->url)
        {
            $identifier = $this->getIdentifier($model);
            $parts      = array(
                'component' => $identifier->package,
                'view'      => $identifier->name,
                'format'    => 'json'
            );

            if ($config->filter) {
                $parts = array_merge($parts, KObjectConfig::unbox($config->filter));
            }

            $config->url = $this->getTemplate()->route($parts, false, false);
        }

        $html = '';
        $html .= $this->getTemplate()->createHelper('behavior')->autocomplete($config);

        $options = array();

        if (is_scalar($config->selected) ? !empty($config->selected) : count($config->selected))
        {
            $selected = $config->selected;

            if(!$selected instanceof KModelEntityInterface)
            {
                $selected = $model->setState(KObjectConfig::unbox($config->filter))
                                  ->setState(array($config->value => KObjectConfig::unbox($selected)))
                                  ->fetch();
            }

            foreach($selected as $entity)
            {
                $options[]  = $this->option(array(
                    'value' => $entity->{$config->value},
                    'label' => $entity->{$config->label},
                    'attribs' => array('selected' => true)
                ));
            }
        }

         $html .= $this->optionlist(array(
            'name'     => $config->name,
            'id'       => $config->id,
            'options' => $options,
            'deselect' => false,
            'select2'  => false,
            'attribs'  => $config->attribs
        ));

        return $html;
    }
```

**Comment by johanjanssens** [comment]
@rmdstudio Good catch, suggested changes have been added. Can you double check if everything now works as it should ?

**Pull request closed without merging**
