### PR TITLE
Blacklist scripts on document template filter

### LINKED ISSUE #547: Blacklist scripts on document template filter
This particular filter https://github.com/joomlatools/joomlatools-framework/blob/master/code/libraries/joomlatools/component/koowa/template/filter/document.php gets pushed when rendering editors on our forms. It ensures that the current selected editor has all the assets loaded to properly fonction on our forms. 

A big problem with the approach is that this will also push any script that got previously added by a system plugin (see issue on support ticket below).

A proper solution for this problem would be to implement some kind of blacklist which would be used by the template filter to avoid pushing some known scripts that cause problems.

We could hardcode some of these in the template filter and/or make use of the /joomlatools-config/docman.php configuration file to push more scripts on the customer site directly.

#### Support tickets

* _ https://secure.helpscout.net/conversation/1677199783/12482/

### PR DESCRIPTION
**Pull request by ercanozkaya**
Closes #547

### Example usage
```
KObjectManager::getInstance()->getIdentifier('com:koowa.template.filter.docuemnt')->getConfig()->append([
    'strip_assets' => [
        '/media/jui/js/jquery.js',
        '/path/to/any/css/file.css',
        '#.*com_content.*#', // NOTE: delimiters CANNOT be /, use any other delimiter like #, ~ etc. 
    ]
]);
```

### CODE REVIEW

**Review by johanjanssens — APPROVED** [review]

**Comment by johanjanssens** [comment]
@ercanozkaya We also need to make sure this is a config option, as we will apply this manually in case the customer needs it or document how to do it.

**Comment by johanjanssens** [comment]
@jebbdomingo Can you re-test and handle the release?

**Review by jebbdomingo — APPROVED** [review]

**Comment by johanjanssens** [comment]
@ercanozkaya @jebbdomingo This issue isn't 100% ready yet, we still need to expose this as a `config.php` setting. We don't have a config.php file for framework yet to override config options easily as we do for DOCman. See: https://github.com/joomlatools/docman/blob/master/code/site/components/com_docman/resources/config/bootstrapper.php#L10

We either need to expose this per extension or add support for a koowa.php file and implement this in the koowa bootstrapper?

**Comment by johanjanssens** [comment]
@ercanozkaya instead of using preg_match, could we use: https://www.php.net/manual/en/function.fnmatch.php seems very useful for this one?

**Pull request merged**
