### PR TITLE
Support for array values in Koowa.Form.addField

### LINKED ISSUE #31: Support for array values in Koowa.Form.addField
If you try to add an array to a form using Koowa.Form.addField right now the values joined by a comma. Make sure it is properly sent as an array.

### PR DESCRIPTION
**Pull request by ercanozkaya**
Closes #31

### CODE REVIEW

**Comment by ercanozkaya** [comment]
@rmdstudio We discussed this a while ago. Can you check the code please to see if it's looking fine?

**Comment by ercanozkaya** [comment]
Note: needs to be merged into Kodekit.

**Comment by rmdstudio** [comment]
@ercanozkaya is this the fix for the listbox issue that required injecting or removing hidden fields to the form? The code in this branch seems to be working when I test all the listboxes and filters.

**Comment by johanjanssens** [comment]
@ercanozkaya Did you merge this already? According to the customer the batch edit isn't fully working yet. @rastin has done some testing. Can you look into that?

**Comment by ercanozkaya** [comment]
@johanjanssens Yes merged already. Now merged into Kodekit as well.

**Comment by johanjanssens** [comment]
Thanks

**Pull request merged**
