### PR TITLE
Do not flush the stream if the response is not streamable

### LINKED ISSUE #15: Do not flush the stream if the response is not streamable
See: https://github.com/timble/kodekit/issues/93

See: https://support.joomlatools.com/forums/topic/6705-bulk-import-files-folders#comment-36948

### PR DESCRIPTION
**Pull request by johanjanssens**
resolve #15

### CODE REVIEW

**Comment by johanjanssens** [comment]
@ercanozkaya  Can you review? This should also be ported to 2.x

**Comment by ercanozkaya** [comment]
@johanjanssens Reviewed the changes. Downloading still works with or without ranges.

**Comment by ercanozkaya** [comment]
Backported to 2.x as well

**Comment by johanjanssens** [comment]
@ercanozkaya We need to open this up again, this change is creating issues with large files. See: 
https://support.joomlatools.com/forums/topic/6705#comment-36067

From @amazeika: I’ve checked the code and we load the whole video on memory before streaming (first response sent back to client). He’s getting a mem error as a consequence (his videos are big). We need a better approach here. Instead of echoing $response->getStream()->toString() on transport we could progressively read the stream in chunks to avoid the memory error.

**Pull request merged**
