### PR TITLE
Merge Feature/240-transliterator

### LINKED ISSUE #240: Transliterator::create returns null on failure
We should check against null on KFilterAscii. See: #187, #236 

#### Support tickets

* https://support.joomlatools.com/tickets/topic/9589
* https://support.joomlatools.com/tickets/topic/9594

### PR DESCRIPTION
**Pull request by ercanozkaya**
Closes #240

### CODE REVIEW

**Comment by johanjanssens** [comment]
@ercanozkaya Should we also merge this to Kodekit?

**Comment by ercanozkaya** [comment]
@johanjanssens The first part should definitely be ported. The fallback is your call.

**Comment by johanjanssens** [comment]
@ercanozkaya Can you port it?

**Comment by ercanozkaya** [comment]
@johanjanssens done

**Pull request merged**
