### PR TITLE
Fix the media path for joomlatools-platform

### PR DESCRIPTION
**Pull request by allanpilarca**
Fix the media path for joomlatools-platform in the template helper ui.

### CODE REVIEW

**Comment by johanjanssens** [comment]
@ercanozkaya @amazeika  Can you double check this and handle the merge? We need this fix in FILEman for Scicasts. This has prio so cannot wait for 3.1. We will need a maintenance release of 3.0 and fw.

**Comment by johanjanssens** [comment]
@allanpilarca There are more places in the framework where we use JPATH_ROOT. Should those also be reviewed? /cc @ercanozkaya

**Comment by amazeika** [comment]
@allanpilarca @johanjanssens @ercanozkaya I would go with these conditional statements. As Johan pointed out there are more JPATH_ROOT in the FW codebase. These need fixing as well.

If we want our FW to run inside the platform, IMHO the platform should ensure that it does, not the other way around. This may be easily fixed by aliasing JPATH_ROOT to JWEB_PATH on the definitions file. If we decide that's the FW that should take care of this, then the FW should have its own set of constants that get declared based on the app where it is running. I'm more fan of the first option as it's the app that should be setting this.

I hope I'm making sense.

**Comment by johanjanssens** [comment]
@amazeika @ercanozkaya The problem we are trying to fix here is specific for JPATH_ROOT.'/media' which is used only in two places:

See: https://github.com/joomlatools/joomlatools-framework/search?utf8=%E2%9C%93&q=JPATH_ROOT.%27%2Fmedia&type=

The second time is only for the installer so it doesn't apply to the platform context. So in this case there is only one code location that needs fixing. We can fix it as @allanpilarca proposes, or we can introduce another define for the media folder location, for example KPATH_MEDIA? That one could be set by the framework as default if not defined earlier. Both approaches work, the second is probably more ideal.

**Comment by amazeika** [comment]
@johanjanssens There are some other files (other than installer files, e.g. bootstraper, template locator, FileSystem Buffer Stream.) where JPATH_ROOT is being used, so I'm surprised that this is only a problem for the UI helper media path.

I just don't like the conditional approach as the more we use it, the less readable the code becomes and harder the maintenance. Either we fix this by introducing a FW constant or we do aliasing. Any approach works. @ercanozkaya thoughts ?

**Comment by johanjanssens** [comment]
The problem is not JPATH_ROOT, the problem is JPATH_ROOT./media. In platform the media folder is not in root its in the /web folder. See: https://github.com/joomlatools/joomlatools-platform/tree/master/web

The UI helper is doing file system checks against JPATH_ROOT which is creating the issue. The fix from @allanpilarca is the most straightforward way to solve this. Since we need this fix now and it's only in once instance I would merge this PR and we can create a ticket to tackle this in a better way if more of these problems occur, but i doubt it.

**Comment by amazeika** [comment]
@johanjanssens Got it, I completely misunderstood the issue. I see it now. Moreover, we are indeed already aliasing JPATH_ROOT to JPATH_WEB in the platform which was what I was suggesting.

Agreed with merge and new ticket to improve later down the road.

**Comment by johanjanssens** [comment]
@ercanozkaya Can you merge this and create a 3.0.x maintenance release of FILEman for @allanpilarca

**Comment by ercanozkaya** [comment]
@johanjanssens @amazeika Merged the branch so @allanpilarca can continue, however KPATH_MEDIA sounds like a good idea to me.

**Comment by johanjanssens** [comment]
@ercanozkaya Agreed, can you make a related ticket to add a KPATH_MEDIA?

**Pull request merged**
