### PR TITLE
Bug in decorator

### LINKED ISSUE #19: Bug in Decorator
`Catchable fatal error: Argument 2 passed to KCommandHandlerAbstract::execute() must implement interface KCommandChainInterface, none given, called in /home/vagrant/Projects/joomlatools-framework/code/libraries/joomlatools/library/controller/toolbar/decorator.php on line 34 and defined in /home/vagrant/Projects/joomlatools-framework/code/libraries/joomlatools/library/command/handler/abstract.php on line 65`

`KControllerToolbarDecorator` doesn't pass the required parameter `$chain` ([see](https://github.com/joomlatools/joomlatools-framework/blob/894dc01c197fdb6d8eb3757032d56fba8aa7db25/code/libraries/joomlatools/library/controller/toolbar/decorator.php#L34)) though `KCommandHandlerAbstract` doesn't use the 2nd argument `$chain` ([see](https://github.com/joomlatools/joomlatools-framework/blob/894dc01c197fdb6d8eb3757032d56fba8aa7db25/code/libraries/joomlatools/library/command/handler/abstract.php#L65))

### PR DESCRIPTION
**Pull request by ercanozkaya**
Closes #19

### CODE REVIEW

**Comment by ercanozkaya** [comment]
@jebbdomingo can you test this please?

**Comment by jebbdomingo** [comment]
@ercanozkaya not part of the bug, just curious why the removal of delegate's toolbar here? https://github.com/joomlatools/joomlatools-framework/blob/7e1a909802743ec58d89da9131287f01cabcffeb/code/libraries/joomlatools/library/controller/toolbar/decorator.php#L57

**Comment by johanjanssens** [comment]
@jebbdomingo I'll explain that tomorrow, the reason for this is that calls need to be run through the decorated toolbar, so you need to remove the delegate and inject the decorator. 

Note: for questions, please use Slack in futur, we don't use Github for questions.

**Comment by jebbdomingo** [comment]
@ercanozkaya tested and working

**Comment by johanjanssens** [comment]
@jebbdomingo @ercanozkaya It seems this PR was never synced with Kodekit?

**Pull request merged**
