### PR TITLE
Merge feature/172-search

### PR DESCRIPTION
**Pull request by ercanozkaya**
For #172

### CODE REVIEW

**Comment by johanjanssens** [comment]
@ercanozkaya This is looking great, the only reservation i have here is that we might be semi-leaking data, you are able to find rows based on column data that might not have been exposed in the UI? We would consider that an issue?

**Comment by ercanozkaya** [comment]
@johanjanssens The columns are limited to what is passed to searchable behavior. If you pass `['title', 'description']` to the behavior only those two are accepted as a prefix and then also id as a universal prefix. This should cover it no?

**Comment by johanjanssens** [comment]
Perfect, missed that. This is a great addition to the framework. Can this also be merged with Kodekit?

**Comment by ercanozkaya** [comment]
All done: https://github.com/timble/kodekit/pull/166

**Pull request merged**
