### PR TITLE
Fix ordering query

### LINKED ISSUE #26: Calculation problem in orderable
When a row is re-ordered with a positive change, other rows' ordering data is not properly updated.

### PR DESCRIPTION
**Pull request by ercanozkaya**
Closes #26

### CODE REVIEW

**Comment by ercanozkaya** [comment]
@rmdstudio Can you test this after you take out the temporary fix in ordering.js?

**Comment by rmdstudio** [comment]
@ercanozkaya I just tested. It is working fine

**Comment by johanjanssens** [comment]
@ercanozkaya Don't forget to move this into Kodekit too?

**Comment by johanjanssens** [comment]
@rmdstudio @ercanozkaya It seems this PR was never synced with Kodekit?

**Pull request merged**
