### PR TITLE
issue #20 Support for non KModelEntityInterface selected items

### PR DESCRIPTION
**Pull request by rmdstudio**
@ercanozkaya could you please test this PR? 

1. go to the documents list in the back-end and filter using a few tags. Then see if the selected items show in the list.
2. edit a document and see if the tags selected items are showing.

Thank you

### CODE REVIEW

**Comment by johanjanssens** [comment]
@rmdstudio Are those the same changes we made for the autocomplete but ported to the listbox?

**Comment by rmdstudio** [comment]
@johanjanssens no it isn't. Those changes had to do with the ability to pass a model object or just the model identifier. This one is for the existing selected items in a list.

**Comment by ercanozkaya** [comment]
@rmdstudio I'm still not sure why we need this. When you pass an entity $config->selected is set by iterating over it. When you pass ```'selected' => parameters()->tag``` for example optionlist handles it perfectly fine down the road as well. 

I also tested the two scenarios you mentioned here and they both work fine without the PR. What is the exact issue you are seeing?

**Comment by rmdstudio** [comment]
@ercanozkaya @johanjanssens  this is what happens before the fix
screen shot 2016-06-10 at 10 17 26 am

and after the fix

screen shot 2016-06-10 at 10 18 51 am

**Comment by ercanozkaya** [comment]
@rmdstudio I found the issue. Your tags are using different title/slugs. Mine were equal. The issue is some fields were using the tag as the value field while some were using the title (the default in com:tags)

I changed the default in com:tags to use the slug for value now. Also streamlined the calls to the helper to make sure they pass the correct entity. This is not happening for me anymore. Can you please check if it's fixed for you as well? Let's continue on this in Docman tags ticket.

**Comment by johanjanssens** [comment]
@ercanozkaya What changes did you make? Those changes will need to be ported to Kodekit too. Also using slugs for tags will not work for new tags, hence I used title. Does that still work?

**Comment by johanjanssens** [comment]
@ercanozkaya @rmdstudio The changes proposed by Rastin here, do make sense, it streamlines the listbox API. Might port them to Kodekit only?

**Comment by ercanozkaya** [comment]
@johanjanssens @rmdstudio  You are right, new tags wouldn't work with this. I reverted the change. Now I use title field for tag edit fields while using slug field for selectors in the menu item, grid etc.

About the changes proposed, these selected options are already generated by the call to the model. We would simply add them twice with this change. Why would we want that?

**Comment by johanjanssens** [comment]
@ercanozkaya Can this branch be deleted? Also are there any changes that need merged to platform for the tags component?

**Comment by ercanozkaya** [comment]
@johanjanssens Yeah it can. No changes necessary to tags as I set the value during the call to the helper, not in tags itself.

**Comment by johanjanssens** [comment]
Excellent. Thanks!

**Pull request closed without merging**
