### PR TITLE
#284: Set focus on element after closing select2 box to preserve tabb…

### LINKED ISSUE #284: Select2 focus fix
When a select2 is closed the tab focus is lost, and the current state in completing the form is forgotten. 

See: https://github.com/joomlatools/leadman/issues/48

### PR DESCRIPTION
**Pull request by ercanozkaya**
Closes #284

### CODE REVIEW

**Comment by ercanozkaya** [comment]
@jebbdomingo can you remove **both CSS and JS** select2 fixes in this ticket https://github.com/joomlatools/leadman/pull/56 and then test this PR please? It should fix them both

**Comment by jebbdomingo** [comment]
@ercanozkaya select2 focus is working properly, however, the scopebar doesn't show up again, it was fixed before.

image

**Comment by ercanozkaya** [comment]
@jebbdomingo can you pull and try again please?

**Comment by jebbdomingo** [comment]
@ercanozkaya test passed

**Pull request merged**
