### PR TITLE
User object should update itself after a login

### LINKED ISSUE #275: User object should update itself after a login
See: https://support.joomlatools.com/tickets/topic/9962

When a user logs in to the system, user singleton still retains its old values for anonymous users.

### PR DESCRIPTION
**Pull request by amazeika**
fixes #275

### CODE REVIEW

**Comment by amazeika** [comment]
@ercanozkaya All yours for review mister.

**Comment by amazeika** [comment]
@johanjanssens Please double check this one when you get the time :)

**Comment by johanjanssens** [comment]
@amazeika This is a related issue: https://support.joomlatools.com/tickets/topic/9962 Need to inform the customer of the fix.

**Comment by amazeika** [comment]
Copy/Paste from slack @johanjanssens 

This ticket started as a Koowa issue. We are fixing two "similar" issues here, one on our end and the other on Joomla's end. The Koowa user was also being instantiated early sometimes and stored int he registry as an default user. This prevented the basic and jwt auth to properly function. Then we had the very same problem on Joomla's end due to the user property not synced in the menu instance. 

The reason why this got moved to a subscriber is that we are basically doing it for other events on the Joomlatools system plugin. @ercanozkaya brought this to my attention and we decided to add a subscriber as well. This was initially added on the system plugin then moved to the subscriber.

**Comment by johanjanssens** [comment]
@amazeika Thanks for the explanation, makes total sense.  All good to go. Next time add this info to the description of the PR it helps to understand the code and why it was implemented as is. The PR can also be easily referenced later in case we forget why something is as it is, it then acts as documentation.

**Pull request merged**
